### ISSUE TITLE
issue with the plot

### ISSUE THREAD

**Issue by andrewcz** [maziarraissi/ParametricGP-in-Python#1]
Hi Awesome repo.
Very cool algorithm.
Just getting issues with the output.

Iteration: 5930, NLML: 10.53, Time: 0.01
Iteration: 5940, NLML: 10.52, Time: 0.01
Iteration: 5950, NLML: 10.52, Time: 0.01
Iteration: 5960, NLML: 10.52, Time: 0.01
Iteration: 5970, NLML: 10.52, Time: 0.01
Iteration: 5980, NLML: 10.52, Time: 0.01
Iteration: 5990, NLML: 10.52, Time: 0.01
Iteration: 6000, NLML: 10.52, Time: 0.02
Predicting the last partition
Traceback (most recent call last):
  File "one_dimensional_example.py", line 91, in <module>
    plt.tight_layout()
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 1366, in tight_layout
    fig.tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 2275, in tight_layout
    pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/tight_layout.py", line 328, in get_tight_layout_figure
    pad=pad, h_pad=h_pad, w_pad=w_pad)
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/tight_layout.py", line 114, in auto_adjust_subplotpars
    tight_bbox_raw = union([ax.get_tightbbox(renderer) for ax in subplots
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/tight_layout.py", line 115, in <listcomp>
    if ax.get_visible()])
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 4164, in get_tightbbox
    bb.append(self.title.get_window_extent(renderer))
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 922, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 309, in _get_layout
    ismath=ismath)
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 232, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 501, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 365, in make_dvi
    texfile], tex)
  File "/home/andrewcz/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 335, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/home/andrewcz/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/andrewcz/anaconda3/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/andrewcz/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/andrewcz/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'latex': 'latex'

**Comment by andrewcz** [comment]
(/home/andrewcz/.cache/matplotlib/tex.cache/199b82c7a8ac6079ac4e7fcc4f08cb46.te
x
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 84 language(s) loaded.

! LaTeX Error: File `article.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.3 \usepackage
               {type1cm}^^M
No pages of output.
Transcript written on 199b82c7a8ac6079ac4e7fcc4f08cb46.log.


apologies i am getting the above error with latex output

**Comment by andrewcz** [comment]
apologies restarted my computer and all fixed.
you can consider this issue closed.
Best,
Andrew

**Comment by maziarraissi** [comment]
Great! Thanks Andrew!
